# Generated by Django 6.1.1 on 2026-09-09 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_city_city_name_en_city_city_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_site.country'),
            preserve_default=False,
        ),
    ]
