# Generated by Django 6.1.1 on 2026-09-16 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0005_userprofile_country_alter_city_city_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
